### ISSUE TITLE
not libhmac.so in v5.11.1

### ISSUE THREAD

**Issue by statist32** [Unbrick/Jodel-Keyhack-v2#1]
Ther is not libhmac.so in v5.11.1. Which file should be used?
I werent able to use your script and get the key.

**Comment by Unbrick** [comment]
Try using libe.so, they are renaming the librarys with every build. Also try using the script [before my latest commit](https://github.com/Unbrick/Jodel-Keyhack-v2/commit/2bb2c97b08c09e05b5f273bdd64005aa07b860fe#diff-dfc6139fe25dd6faeb015706a9e61f7d), somehow the instruction set got screwed up in betweeen.
