### ISSUE TITLE
how can I use it with Linux?

### ISSUE THREAD

**Issue by guitar9** [Unbrick/Jodel-Keyhack-v2#2]
how can I use it with Linux?

**Comment by Unbrick** [comment]
Compile the decryption part using GCC to a Linux shared object and change the corresponding lines in the python file. Also you need of course the IDA Linux version.

**Comment by guitar9** [comment]
not know what you exactly mean. dll files are for Windows. So i need to transfer the dll file?

**Comment by Unbrick** [comment]
Should be fixed for you now (i know a little late) but now it runs in purely python.
